### ISSUE TITLE
Could testimonials link back to the company websites?

### ISSUE THREAD

**Issue by aviaviavi** [haskell-infra/www.haskell.org#118]
So cool to see the testimonials on the live site! Any chance they could link back to the company home pages? I'd be happy to send a pull request myself if so.

**Comment by TikhonJelvis** [comment]
That makes sense, but seems like it could look a bit like an ad or endorsement. How can we avoid even the appearance of something like that?

One idea could be linking to short articles or technical blogs about how the company uses Haskell—a way to "show" rather than "tell" about Haskell for both the company *and* haskell.org. Except for consulting companies, linking to something more specific than the general company page seems a lot more relevant *in this specific context*.

**Comment by aviaviavi** [comment]
Interesting perspective. To be clear though, I'm not actually advocating we change the appearance of this part of the page. I'm simply suggesting we make those company logos hyperlink back to the home page of each company. 

To share my own, in my experience, it's quite common to link back to a company landing page any time you have a testimonial or company logo embedded on a site. That way, visitors can easily learn more about the company behind the quote and assess if their own use case will be similar. So I think it could actually make the testimonials land more effectively with readers. 

So overall, I personally don't agree it would look like an advertisement (especially since this doesn't advocate for any visual change at all), but I certainly understand the reasoning behind the concern. To me, an additional concern would be a reader doing a google search for the company behind a given quote, and then accidentally ending up in the wrong place.

Either way, thanks for considering!

**Comment by tomjaguarpaw** [comment]
I agree with Avi. Linking to the company doesn't suggest advertisement or endorsement to me. In fact if I came across a collection of testimonials like this my first instinct would be try to click a link to verify that the companies are not just made up lorem ipsum placeholders (or worse).

**Comment by TikhonJelvis** [comment]
Okay, that makes sense to me.

@aviaviavi, if you'd like to put together a PR for this, please go ahead :).

**Comment by aviaviavi** [comment]
Ok great will do!
