### ISSUE TITLE
Add outdated warning to old Haddock documentation that is among top search results on Google

### ISSUE THREAD

**Issue by malteneuss** [haskell-infra/www.haskell.org#148]
Is it possible to add a warning to the old Haddock docs that those are outdated, and to add a link the latest docs? Or do an immediate redirect? It tripped me up (and others i know as well) in thinking this was the latest Markup syntax, because its links appear at the top of search results (at least on my machine):
![haskell_haddock_search_results](https://user-images.githubusercontent.com/5301202/145479514-e48cdf1e-4c29-4090-8d09-b81318d1e724.png)

As an alternative, we could try to demote its page rank somehow.

**Comment by tomjaguarpaw** [comment]
I agree that outdated documentation makes navigating the Haskell world treacherous. According to the work-in-progress PR to classify the subsites of haskell.org [the Haddock subsite](https://github.com/haskell-infra/www.haskell.org/pull/103#issuecomment-877643716) is owned by the Haddock maintainers. We should file an issue on [the Haddock Github page](https://github.com/haskell/haddock/) to ask what they want to do (though please keep this issue open until we have a resolution). If you'd like to file it @malteneuss then please do, otherwise I'll do when I get round to it. I suspect the Haddock maintainers will want to

1. update that documentation to the latest version, or
2. insert a redirect to the latest version hosted elsewhere (if it is -- does anyone know)

**Comment by malteneuss** [comment]
@tomjaguarpaw i would be nice for you to file an issue as you seem to know the maintainers already.

**Comment by tomjaguarpaw** [comment]
Requested of the infra admins: https://github.com/haskell-infra/haskell-admins/issues/7
