### ISSUE TITLE
Please reveal the source/mechanics of the `alex` and `happy` subsites

### ISSUE THREAD

**Issue by andreasabel** [haskell-infra/www.haskell.org#183]
There is no information on what `alex/` or `happy/` redirect to, and where their source is hosted.
https://github.com/haskell-infra/www.haskell.org/blob/087e788432b59b5c99b98306b928a67533cd831f/README.md?plain=1#L149-L150

Context: 
- https://github.com/haskell/alex/issues/204

**Comment by tomjaguarpaw** [comment]
The sources are not known, and the mechanics of how they are hosted are that they are just HTML files on the www.haskell.org server. I'm not sure who, if anyone, knows more than that. Maybe Simon Marlow? In any case there is no well-understood procedure for updating them or for grating the authority for them to be updated. (Highlighting this is part of the reason I made the subsites table in the first place.)

**Comment by andreasabel** [comment]
Thanks @tomjaguarpaw for the quick reply!  So likely it is @simonmar who has been handling this.

> HTML files on the [www.haskell.org](http://www.haskell.org) server.

If I wanted access to this server, how would I go about?

**Comment by tomjaguarpaw** [comment]
>  So likely it is @simonmar who has been handling this.

Yes, but perhaps last 10 years ago.

> If I wanted access to this server, how would I go about?

Taking your question literally, I think you would have to be elected to the Haskell.org committee, become a [Haskell Infrastructure admin](https://github.com/haskell-infra/haskell-admins), or some other how have the admins grant you access.

But if you're asking because you want to change the `alex/` and `happy/` subsites, the most direct route is probably to lobby various stakeholders to persuade them that a change is warranted, and then submit a PR to [www.haskell.org](https://github.com/haskell-infra/www.haskell.org/pulls) to change them to something else. It doesn't really matter where the old source is, given that we can just replace it with something else.

**Comment by gbaz** [comment]
The easiest way to get access to maintain any subsite is to show "hey, an existing person responsible for the project/site has said I should have access" and the admins will hook you up immediately.

There's nothing in the least confusing or difficult about it. We do it frequently. I don't know why people insist on believing that it is at all hard or time consuming.

**Comment by tomjaguarpaw** [comment]
@gbaz I'm not sure exactly what you're responding to. I'm sorry if I gave you the impression that I think the infra-admins make things slow or time-consuming. That's not what I meant. Actually, what is difficult is finding out *who* is responsible for the project and convincing them to do anything about the current state of their project subsite.

For example, it took nearly six months (Dec 20 - May 21) for me to get some small, uncontroversial, PRs merged into the cabal subsite [[example](https://github.com/haskell/cabal-website/pull/15)]. I guarantee to you that _I_ found that confusing, difficult, hard and time consuming. In fact I found the whole process so absurdly frustrating that I joined the Haskell.org committee to try to help improve things.

Now, again, I don't blame the infra-admins for this. Who is to blame? Well, it's not really clear, because there is a vast void of authority, leadership, responsibility, initiative and accountability around most of the www.haskell.org subsites. _That_ is the problem.

**Comment by gbaz** [comment]
I see your point. The problem there is you were trying to get _someone else_ to update the site, and nobody was stepping up to do it, and so it languished. Getting permission to update the site yourself by volunteering is in that sense much easier.

**Comment by tomjaguarpaw** [comment]
Well then, I think one answer to @andreasabel's question is:

You ask John Ericson @Ericson2314 and Vladislav Zavialov @int-index (the only active maintainers of happy and alex) to share with you their authority over that subsite.  Then you can do with it as you wish. I suggest you do one of the following:

* Ask the infra-admins to establish redirects from the subsite to a separately-maintained up-to-date alternative (for example on readthedocs.io) (this is the option [chosen by Haddock](https://github.com/haskell/haddock/issues/1443))

* Move the subsite into the [www.haskell.org repo](https://github.com/haskell-infra/www.haskell.org/) (then it can be kept up-to-date by our normal PR, CI and deploy process)

**Comment by askeblad** [comment]
> for example on readthedocs.io

maybe not a good fit as per [#195](https://github.com/haskell/happy/issues/195)

alex webpage has link [Online (HTML)](https://www.haskell.org/alex/doc/html/index.html)

happy webpage has link [Online Documentation](https://www.haskell.org/happy/doc/html/index.html)

code for respective packages' User Guide(s) not written in .rst files

**Comment by andreasabel** [comment]
@gbaz
> The easiest way to get access to maintain any subsite is to show "hey, an existing person responsible for the project/site has said I should have access" and the admins will hook you up immediately.

I sent my SSH key to @bgamari in reference to https://github.com/haskell/happy/issues/122#issuecomment-578967255.
Should I send it to you as well/instead?

**Comment by gbaz** [comment]
Ben, davean or myself can do it for you. Typically one emails admin at haskell dot org to get in contact with the admin group. That said, it would be good to have some indication of signoff from a current maintainer of these packages that they're aware of this and fine with you getting upload permissions.

**Comment by ketzacoatl** [comment]
@andreasabel / @tomjaguarpaw, would this not be a great place to use CI to build and update the contents of the site for us? Why are we limited to SSH and manual file uploads for managing this content?

**Comment by gbaz** [comment]
to close this out, ben, andreas, and john now all have ssh perms for the two subsites.

**Comment by tomjaguarpaw** [comment]
> would this not be a great place to use CI to build and update the contents of the site for us?

Yes it would. I would be happy to incorporate the `happy` and `alex` subsites into the main `www.haskell.org` repo so it can take advantage of our CI and automated deployment. That decision is up to the subsite owners though.

> Why are we limited to SSH and manual file uploads for managing this content?

Well, I suppose because it requires work and buy-in to do anything different.

**Comment by ketzacoatl** [comment]
> That decision is up to the subsite owners though.

Good point, who are the owners / who do we speak to? Is this for the CLC to consider?

**Comment by tomjaguarpaw** [comment]
That is, Ben Gamari, Andreas Abel, John Ericsson.

**Comment by askeblad** [comment]
https://github.com/haskell/alex/issues/204#issuecomment-1061051065

friendly reminder if anyone wants to use the code from a validated update

**Comment by andreasabel** [comment]
I now added source info for `/alex`:
- https://github.com/haskell-infra/www.haskell.org/pull/193

@tomjaguarpaw wrote:
> > would this not be a great place to use CI to build and update the contents of the site for us?
> 
> Yes it would. I would be happy to incorporate the `happy` and `alex` subsites into the main `www.haskell.org` repo so it can take advantage of our CI and automated deployment. That decision is up to the subsite owners though.

Speaking for `alex` (where I am currently working on website/docs), I'd be happy to follow your suggestion.  I suppose I could get edits in via simple PRs then.  Atm, `/alex` is just one `index.html` file (which does not contain anything that could not also live in the docs).
See also 
- https://github.com/haskell/alex/issues/215

where I suggest to make `/alex` a simple redirect to the docs hosted on RTD.

**Comment by askeblad** [comment]
@andreasabel should I make a PR

**Comment by tomjaguarpaw** [comment]
@andreasabel I believe this issue has been resolved. If so, please close. If not, please clarify. Otherwise I'll close this as a formality in due course.

**Comment by Ericson2314** [comment]
I have now converted the Happy docs to readthedocs.com so we may want to do a redirect for Happy and Alex alike.

In the interim I would be happy to see the HTML just put in this repo instead, while we do a final pass to make sure the docs have everything in the website or similar.

**Comment by tomjaguarpaw** [comment]
> In the interim I would be happy to see the HTML just put in this repo instead, while we do a final pass to make sure the docs have everything in the website or similar.

Great, thanks! Sounds like a good solution to me. Please drive forward those PRs :)
