### ISSUE TITLE
Links look not that good (in Chrome), troubles with styles?

### ISSUE THREAD

**Issue by metacortexplus** [haskell-infra/www.haskell.org#58]
There are dotted underlines under links.

![Screenshot from 2021-01-09 10-24-18](https://user-images.githubusercontent.com/21023720/104087008-3805a280-5265-11eb-9573-beccdaf4c226.png)

**Comment by TikhonJelvis** [comment]
Yeah, some of those links look a bit off.

We added the dotted underline to help visually distinguish links inside body text—the purple and black color scheme didn't have enough contrast otherwise, and a full underline looked rather dated.

How can we visually distinguish the links in a way that looks better?

If the main problem is that the video links specifically look bad, I imagine we could have some dedicated styling for the video cards specifically that makes it clear that they are clickable without needing the underline.

**Comment by emtes** [comment]
**Suggestion: This issue to be closed with a PR addressing the navigation link color contrast issue**

Why?
- I can't reproduce any dotted underlines using Chrome or Firefox.
- The contrast between the nav links does not meet WCAG 2 AA contrast ratio requirements.
    - **Mitigation:** Darken until standard is met with `#717171`
    - **Question:** Do we think the links still need to be distinguished more? I think having them be bold or underlined with a solid line are both great options.

I'm happy to pick this up if the reframing and proposed mitigation sound good.

![Screenshot from 2023-07-18 14-17-32](https://github.com/haskell-infra/www.haskell.org/assets/54204155/eeb776c4-d721-4fbd-80af-4a9683a887d5)

**Comment by TikhonJelvis** [comment]
The link styling was updated a few weeks ago in #271.

The contrast issue is definitely worth fixing. Your suggested color for the navigation menu looks great to me. I was mostly thinking about distinguishing links in body text rather than the nav menu, and those seem fine with the solid underline that they have today.

**Comment by emtes** [comment]
Perfect! And great thread in the linked issue, it would indeed be nice to have some input from a designer. Small, isolated fixes could introduce a lot of visual inconsistency.
